baseline:
    algo: ppo
    n_envs: 8
    n_steps: 128
    epoch: 4
    mini_batch_per_epoch: 4
    mini_batch_size: 256
    gamma: 0.99
    lmbda: 0.95
    learning_rate: 0.00025
    grad_clip_norm: 0.5
    eps_clip: 0.1
    value_coef: 0.5
    entropy_coef: 0.01
    normalize_adv: True
    normalize_rew: False
    use_gae: True
    architecture: nature
